### ISSUE TITLE
[Algo] N Queen in Python

### ISSUE THREAD

**Issue by skahk** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#107]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name: Backtracking (n-queen problem)** 

- **Programming Language: Python** 

- **Time complexity: O(n^n)** 

**Is this your first contribution to this repository?**
No

**Comment by bmusuko** [comment]
can i try this ?
