### ISSUE TITLE
[DS] Heap in C++

### ISSUE THREAD

**Issue by shivasinghal2000** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#131]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:**  Heap

- **Programming Language:** C++

**Is this your first contribution to this repository?**
Yes

**Comment by dheeraj07** [comment]
Can I take this up?

**Comment by shivasinghal2000** [comment]
Solved this issue
