### ISSUE TITLE
[DS] Linked List in C++

### ISSUE THREAD

**Issue by AMosa3d** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#145]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** Linked List

- **Programming Language:** C++

**Is this your first contribution to this repository?**
Yes

**Comment by vincentalfred** [comment]
Hi
I would like to take up this issue

**Comment by frextrite** [comment]
Hi @vincentalfred, I believe @AMosa3d wants to work on this. You can pick up any other algo/ds that has not already been implemented and create an issue for it. A maintainer will assign you to it 😄

**Comment by frextrite** [comment]
Implemented in #160
