### ISSUE TITLE
[Algo]Longest Common Subsequence using dynamic programming

### ISSUE THREAD

**Issue by Bevin7** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#157]
# Algorithm Longest common subsequence

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:**Dynamic Programming (Longest Common Subsequence)

- **Programming Language:** Python

- **Time complexity:** O(mn)

**Is this your first contribution to this repository?**
Yes

**Comment by raffleberry** [comment]
I would like to work on this.
