### ISSUE TITLE
[DS] Linked List

### ISSUE THREAD

**Issue by aht360** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#163]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** 
Linked List
- **Programming Language:** 
C

**Is this your first contribution to this repository?**
No

**Comment by frextrite** [comment]
@aht360 There is already a PR for linked list in C. Sorry for this but could you work on some other algo/ds? Thanks!
