### ISSUE TITLE
[DS]Adding Queue code written in C

### ISSUE THREAD

**Issue by rounaksarda** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#178]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** 
Queue

- **Programming Language:** 
C

**Is this your first contribution to this repository?**
Yes

**Comment by LIGHT1210** [comment]
I wanna contribute for it

**Comment by rounaksarda** [comment]
I contributed successfully . so closing this issue
