### ISSUE TITLE
[Algo] Bubblesort in Kotlin

### ISSUE THREAD

**Issue by tatocaster** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#181]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** BubbleSort 

- **Programming Language:** Kotlin

- **Time complexity:** O(n2)

**Is this your first contribution to this repository?**
Yes

**Comment by varun514** [comment]
I'll take up this issue

**Comment by frextrite** [comment]
Hey @tatocaster are you working on this?

**Comment by tatocaster** [comment]
Yes will do PR

**Comment by tatocaster** [comment]
looks like someone did the PR already
