### ISSUE TITLE
BFS DFS C++ [Algo]

### ISSUE THREAD

**Issue by asah27** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#195]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** BFS DFS for solving matrix related problems

- **Programming Language:**  C++

- **Time complexity:** O(V+E)

**Is this your first contribution to this repository?**
Yes

**Comment by frextrite** [comment]
BFS DFS for C++ has been implemented. However, if you want to show how to solve matrix related problems, you are free to implement this. 🚀
