### ISSUE TITLE
[DS] Stack in Python

### ISSUE THREAD

**Issue by hungpham2202** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#208]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** Stack

- **Programming Language:** Python

**Is this your first contribution to this repository?**
Yes

**Comment by bull0n** [comment]
Can I take it? Is it available?

**Comment by hungpham2202** [comment]
> Can I take it? Is it available?

I already had it finished on my branch, currently waiting for maintainers to assign it and create a pull request.
