### ISSUE TITLE
[Algo] Ternary Search in C++

### ISSUE THREAD

**Issue by agarwal-akash** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#228]
# Algorithm

- [x ] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** Ternary search

- **Programming Language:** C++
 
- **Time complexity:** O(log<sub>3</sub>N)

**Is this your first contribution to this repository?**
Yes

**Comment by banrovegrie** [comment]
Hey, I would like to contribute to this.

**Comment by frextrite** [comment]
Already implemented in #14
