### ISSUE TITLE
[Algo] Counting Sort in C++

### ISSUE THREAD

**Issue by hungpham2202** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#233]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** Counter Sort

- **Programming Language:** Cpp

- **Time complexity:** O(n)

**Is this your first contribution to this repository?**
No

**Comment by GOYALAYUSH782** [comment]
hey I would like to provide the code and algo for it! So, is it open?

**Comment by hungpham2202** [comment]
Could any maintainers please assign me this issue so I can work on it?
