### ISSUE TITLE
[Algo]Extended Euclidean 

### ISSUE THREAD

**Issue by mittalsaurab** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#237]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** Extended Euclidean

- **Programming Language:** c++

- **Time complexity:** O(log(max(a,b))

**Is this your first contribution to this repository?**
No

**Comment by rvk7895** [comment]
I would like to work on this.TIA
