### ISSUE TITLE
[Algo] Binary Exponentiation in C++

### ISSUE THREAD

**Issue by Groverkss** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#246]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Binary Exponentiation** 

- **c++** 

- **O(logn)** 

**Is this your first contribution to this repository?**
Yes

**Comment by gsc2001** [comment]
I want to work on this

**Comment by 26Vinayak** [comment]
i would like to work on it
