### ISSUE TITLE
[Algo]Binary Exponentiation in C

### ISSUE THREAD

**Issue by Aakash-AA** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#247]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:Binary Exponentiation** 

- **Programming Language C:** 

- **Time complexity: O(log n)** 

**Is this your first contribution to this repository?**
Yes

**Comment by shreygupta2809** [comment]
i would like to contribute to this project

**Comment by frextrite** [comment]
Hi @Aakash-AA this algorithm has already been implemented.
