### ISSUE TITLE
Quicksort

### ISSUE THREAD

**Issue by godcrampy** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#25]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** Quicksort 

- **Programming Language:** C++

- **Time complexity:** O(n*log(n))

**Is this your first contribution to this repository?**
Yes

**Comment by Laronk** [comment]
On it!

**Comment by frextrite** [comment]
Same for this @Laronk, please don't work on issues w/o getting assigned to them.

@godcrampy Thank you for creating this issue and I'm sorry someone started working on it. I would encourage you to pick up some other DS/Algo (there're plenty left), create an issue and ping me, I'll be glad to assign it to you.
