### ISSUE TITLE
[Algo] Fast Exponentiation

### ISSUE THREAD

**Issue by sm2bhat** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#276]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:**  Fast Exponentiation 

- **Programming Language:**  C

- **Time complexity:** O(log n)

**Is this your first contribution to this repository?**
Yes

**Comment by sm2bhat** [comment]
Can I try this?

**Comment by anmolagarwal999** [comment]
Can i take this up ?
