### ISSUE TITLE
[Algo] Selection Sort in Java

### ISSUE THREAD

**Issue by stnbnvdz** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#300]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** Selection Sort

- **Programming Language:** Java

- **Time complexity:** O(n2)

**Is this your first contribution to this repository?**
Yes

**Comment by sriramdasavage** [comment]
Can I take this?

**Comment by stnbnvdz** [comment]
> Can I take this?

Hi. Please read the instruction of the Maintainers on how to contribute on this repo. Tnx

**Comment by frextrite** [comment]
Hey @stnbnvdz, this algorithm is already under review. Can you please work on some other language or maybe some other algorithm? Thanks!

**Comment by frextrite** [comment]
Implemented in #266

**Comment by frextrite** [comment]
We are sorry for the confusion, we surely need a system to track which algorithms/ds are already implemented/are under review.

**Comment by stnbnvdz** [comment]
It's okay. I'll work on another algorithm. Thanks btw!
