### ISSUE TITLE
Create Binary Tree Using java[DS]

### ISSUE THREAD

**Issue by vyom153069** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#391]
# Data Structure

- [ ] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** 

- **Programming Language:** 

**Is this your first contribution to this repository?**
Yes

**Comment by Kuljeet-123** [comment]
@vyom153069 I would like to do this ,please assign me this.

**Comment by Kuljeet-123** [comment]
@vyom153069 please review my PR and merge into your repo and my PR id is #393 .
