### ISSUE TITLE
0-1 knapsack problem

### ISSUE THREAD

**Issue by afAditya** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#6]
# Algorithm 0-1 knapsack problem

- [ ] I have gone through the repository and made sure this algorithm has not been implemented

## Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack

- **Algorithm Name:0-1 knapsack problem**
 
- **Programming Language:c++** 

- **Time complexity:O(nW) where n is the number of items and W is the capacity of knapsack.** 

**Is this your first contribution to this repository?**
Yes

**Comment by cinfinit** [comment]
May i take this one ?

**Comment by frextrite** [comment]
Hey @afAditya are you working on this?

**Comment by afAditya** [comment]
yeah I am working on this

**Comment by afAditya** [comment]
@frextrite you can review my pr #12

**Comment by frextrite** [comment]
Implemented in #12
