### ISSUE TITLE
[DS] Binary Search Tree in C++

### ISSUE THREAD

**Issue by frextrite** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#68]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** Binary Search Tree

- **Programming Language:** C++

**Comment by soumyaukil** [comment]
Please assign me the task.

**Comment by 287mdsahil** [comment]
Since there hasn't been any development in this, can I work on it?

**Comment by frextrite** [comment]
@287mdsahil this has already been implemented in #137
