### ISSUE TITLE
[DS] Stack in C++ (w/o STL)

### ISSUE THREAD

**Issue by frextrite** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#70]
# Data Structure

- [x] I have gone through the repository and made sure this data structure has not been implemented

## Information about my new data structure

- **Data Structure:** Stack

- **Programming Language:** C++

**Comment by 287mdsahil** [comment]
I would like to work for it.

**Comment by frextrite** [comment]
@287mdsahil Go ahead 🚀
