### ISSUE TITLE
[Algo] Graph Search - Breadth First Search and Depth First Search 

### ISSUE THREAD

**Issue by cjtaylor1990** [frextrite/Data-Structures-Algorithms-Hacktoberfest-2K19#73]
# Algorithm

- [x] I have gone through the repository and made sure this algorithm has not been implemented

## Information about my new algorithm

- **Algorithm Name:** 
Breath First Search
Depth First Search

- **Programming Language:** 
Python 3

- **Time complexity:** 
O(V + E)
O(V + E)
V = vertex, E = edge

**Is this your first contribution to this repository?**
Yes

**Comment by cjtaylor1990** [comment]
I could also do this is Javascript too if you'd like, as JS is an accepted language but it doesn't seem to be being used very much among contributors.

**Comment by frextrite** [comment]
@cjtaylor1990 Sure if you want to implement in javascript, please go ahead. Just make sure to make 2 PRs 😄

**Comment by cjtaylor1990** [comment]
@frextrite Just put in two PRs, one for each language. There seems to be an issue with one of your automated tests, as it seems to be being triggered for everyone.

**Comment by frextrite** [comment]
@cjtaylor1990 Ah yes, that needs to be fixed. I'll be reviewing your PRs in a moment.

**Comment by frextrite** [comment]
Implemented in #133
